### PR TITLE
Fix collection tree renaming background color

### PR DESCRIPTION
**Pull request by windingwind**
fix: #3827

after #3828

### CODE REVIEW

**Comment by dstillman** [comment]
Not quite right:

Screenshot 2024-03-11 at 2 09 30 AM

I think there needs to be some sort of border, like on macOS:

Screenshot 2024-03-11 at 2 10 14 AM

**Comment by windingwind** [comment]
does it look right now?

image

(it's rebased on #3828, which is what i mean by `after 3828`)

**Comment by dstillman** [comment]
Hmm, in the screenshot that looks thicker on the top, no?

**Comment by windingwind** [comment]
MacOS:

Comfortable:

image
image


Compact:

image

image


Windows:

Comfortable:

image

image


Compact:

image

image

**Pull request merged**
