### PR TITLE
Better handling of proxies in translators

### PR DESCRIPTION
**Pull request by aurimasv**
Re https://forums.zotero.org/discussion/42163/remove-proxy-information-from-url-field-on-import/

### CODE REVIEW

**Comment by aurimasv** [comment]
https://forums.zotero.org/discussion/45778/bug-isi-web-of-knowledge-records-are-not-saved-but-refs-citing-them-are/ presents another issue with proxies (that, I think, this PR resolves). Currently, it seems that proxies can be double-proxied if doPost/doGet/etc. are performed with proxied URIs. I'll fix this in the translator, but this gives me an opportunity to bump the PR. (I'm aware that it needs to be rebased, which I'll do after getting some comments)

**Comment by aurimasv** [comment]
Actually nvm the above. This patch doesn't touch proxies in connector mode (TODO). #627 addresses that issue.

**Comment by aurimasv** [comment]
It seems to me that it would be best to strip proxies for file/link attachments for display in the right-hand pane in Zotero. We would obviously need to keep proxies for actual download during import. After import, proxying of URLs should be handled dynamically by Zotero client. The current model doesn't work well with sharing file/link attachments.

**Comment by dstillman** [comment]
When you say strip for display, you mean strip for storage, right? We shouldn't be storing proxied URLs at all, should we?

**Comment by aurimasv** [comment]
Right. We just can't do it before downloading

**Comment by aurimasv** [comment]
@dstillman, are you generally OK with this PR? If so, I'll get this ready for merging and include proxy stripping for attachments as discussed above.

**Comment by aurimasv** [comment]
@dstillman, bump bump bump

**Comment by dstillman** [comment]
Sorry, not my department.

**Comment by aurimasv** [comment]
@simonster to the rescue!

**Comment by Demonax** [comment]
Any updates on getting this patch merged? I just spent an hour cleaning out proxy strings from my URLs and it'd be nice not to have to do that again. Cheers!

**Pull request closed without merging**
