### PR TITLE
[COinS export]: Avoid exporting editors, translators, etc.

### PR DESCRIPTION
**Pull request by zuphilip**
Discussed at https://forums.zotero.org/discussion/50880/every-contributor-exported-as-author-in-coins-export/#Item_0

 * Contributors which are not authors, such as editors, translators etc., are not anymore exported to au, aufirst, aulast.
 * These contributors cannot be saved in COinS format at all.
 * Fixed export for corporate authors (aucorp).
 * Changed nonexisting attribute "isInstitution" with "fieldMode".

This affects the COinS export as well as the OpenUrl resolving.

### CODE REVIEW

**Comment by aurimasv** [comment]
Could you create this PR against #537? Then we (or I) will also add unit tests to cover both PRs

**Comment by zuphilip** [comment]
I could make a PR into your branch https://github.com/aurimasv/zotero/tree/coins which is connected to the other issue. Is that what you suggest?

**Comment by aurimasv** [comment]
Yes, that's what I meant.

**Comment by zuphilip** [comment]
Here it is https://github.com/aurimasv/zotero/pull/27

**Pull request closed without merging**
