### PR TITLE
Implement Select Items dialog redesign

### LINKED ISSUE #4320: Update Select Items Dialog
The mock was made a long time ago, but the dialog hasn't been updated yet, and I don't see an open issue or PR.

Current Dialog:

Screenshot 2024-07-02 at 14 20 52

Mock:

select-items-dialog

### PR DESCRIPTION
**Pull request by AbeJellinek**
Looks neat!

Screenshot 2024-07-18 at 3 55 33 PM

I didn't touch the other dialogs that use the same infrastructure (classic Add Citation, Edit Bibliography). The latter, at least, could do with a touch-up, but I don't think we have a mockup for that yet.

Closes #4320

### CODE REVIEW

**Comment by yexingsha** [comment]
Looks good! Just a few changes to make:

1. Now that I see it in action, I feel like the collections tree container should keep to the same horizontal padding as in the main window, so that makes `padding: 16px 0px;`
2. Let's set the default width of this dialog to 800px so that there's more space for the item tree.
3. The spacing between the Cancel and OK buttons should be 8px, and the padding around them should be 16px.

As for Add Citation and Edit Bibliography, there is a comprehensive redesign of word processor plugin in the works (you can see the mocks in the "word processor plugin" page in Figma), but I haven't gotten around to Edit Bibliography yet. I will put it on my list.

**Comment by windingwind** [comment]
Charming interface! I use this dialog a lot in my plugins and this is definitely a big improvement.

**Comment by yexingsha** [comment]
Looks good!

**Comment by ramonmi** [comment]
There are no rounded corners (similar to other dialog boxes in Win11) in the new dialog UI of beta 107, and the border is missing. It is not consistent with the preview in https://github.com/zotero/zotero/pull/4406#issue-2417292213.
image

**Pull request merged**
