### PR TITLE
fx102: Cleans up scss files, removes shadow DOM use from CEs

### PR DESCRIPTION
**Pull request by adomasven**
Removes a huge amount of excessive files and duplication for CE scss. All CE css is now output in the single
zotero-react-client.css file.

Moving all CE styling into a single stylesheet required removing their shadow DOMs. It is desirable anyway, since you want to be able to style CEs from "outside", when embedding in different contexts.

Shadow removal required some CE code changes to maintain functionality.

Elements refactored:
- attachment-box (displayed when an attachment (like PDF) is selected in the item tree)
- color-picker (in the tag color selector)
- guidance-panel (displayed on first run when editing authors for a book section)
- item-box (info tab in the item pane)
- note-editor
- notes-box (note tab in the item pane)
- quick-search-textbox
- related-box (related tab in the item pane)
- tags-box (tags tab in the item pane)
- zoterosearch (advanced search condition builder form)

I've hand-tested all these elements to make sure they work. Some, like zoterosearch have tests but they were failing before these changes too.

### CODE REVIEW

**Comment by dstillman** [comment]
We should take this opportunity to rename the main file something other than zotero-react-client.css. Like…zotero.css? (We have another zotero.css but it's at a different path and the file in the repo will be zotero-{platform}.scss anyway and eventually we'll presumably just move everything in zotero.css over to files in the scss dir.)

**Comment by dstillman** [comment]
Build error:

```
Error: Error: Failed on scss/zotero-react-client-unix.scss: Error: Can't find stylesheet to import.
   ╷
17 │ @import "linux/menupopup";
```

**Comment by adomasven** [comment]
> Build error:
> 
> ```
> Error: Error: Failed on scss/zotero-react-client-unix.scss: Error: Can't find stylesheet to import.
>    ╷
> 17 │ @import "linux/menupopup";
> ```

Yep, fixing it now, along with file renaming.

**Comment by adomasven** [comment]
This is now done, but after rebase on top of the latest fx102 I already see commits from Tom that break the pattern established here, so it would be good to merge this sooner than later. I also have Linux styling fixes that I want to push on top of this.

**Comment by dstillman** [comment]
I'm seeing this in the console:

```
Uncaught TypeError: DocumentL10n.connectRoot: Argument 1 is not an object.
    connectedCallback chrome://zotero/content/elements/base.js:47
    connectedCallback chrome://zotero/content/elements/itemBox.js:113
    _addItemContext chrome://zotero/content/contextPane.js:971
5 base.js:47:21
    connectedCallback chrome://zotero/content/elements/base.js:47
    connectedCallback chrome://zotero/content/elements/itemBox.js:113
    _addItemContext chrome://zotero/content/contextPane.js:971
    AsyncFunctionNext self-hosted:632

```

**Comment by dstillman** [comment]
Looks like I get the above every time I open a new child PDF in the reader.

**Comment by dstillman** [comment]
Oh, sorry, that's not new with this commit.

**Comment by dstillman** [comment]
Er, yes it is — sorry, getting tickets confused here.

**Comment by dstillman** [comment]
Also an error logged in Advanced Search

```
Uncaught TypeError: DocumentL10n.connectRoot: Argument 1 is not an object.
    connectedCallback chrome://zotero/content/elements/base.js:47
    addCondition chrome://zotero/content/elements/zoteroSearch.js:121
    set search chrome://zotero/content/elements/zoteroSearch.js:111
    onLoad chrome://zotero/content/advancedSearch.js:55
    tryCatcher resource://zotero/bluebird/util.js:16
    _settlePromiseFromHandler resource://zotero/bluebird/promise.js:547
    _settlePromise resource://zotero/bluebird/promise.js:604
    _settlePromiseCtx resource://zotero/bluebird/promise.js:641
    _drainQueueStep resource://zotero/bluebird/async.js:97
    _drainQueue resource://zotero/bluebird/async.js:86
    _drainQueues resource://zotero/bluebird/async.js:102
    drainQueues resource://zotero/bluebird/async.js:15
base.js:47:21
    connectedCallback chrome://zotero/content/elements/base.js:47
    addCondition chrome://zotero/content/elements/zoteroSearch.js:121
    set search chrome://zotero/content/elements/zoteroSearch.js:111
    onLoad chrome://zotero/content/advancedSearch.js:55
    tryCatcher resource://zotero/bluebird/util.js:16
    _settlePromiseFromHandler resource://zotero/bluebird/promise.js:547
    _settlePromise resource://zotero/bluebird/promise.js:604
    _settlePromiseCtx resource://zotero/bluebird/promise.js:641
    _drainQueueStep resource://zotero/bluebird/async.js:97
    _drainQueue resource://zotero/bluebird/async.js:86
    _drainQueues resource://zotero/bluebird/async.js:102
    drainQueues resource://zotero/bluebird/async.js:15

```

**Comment by dstillman** [comment]
Looking good otherwise

**Comment by adomasven** [comment]
Fixed.

**Pull request merged**
