### PR TITLE
Improve keyboard navigation in PDF reader tab

### PR DESCRIPTION
**Pull request by mrtcode**
Let's try this out.

- Toolbar navigation is now continuous.
- Improved notes list navigation.
- Toggling Item/Notes split button focuses context pane, even when doing so with mouse (which is not necessary good).

#2379

### CODE REVIEW

**Comment by mrtcode** [comment]
We can try this out again.

Although I still need to fix RTL mode. Also there is a strange border (which was all the time?) below Item/Notes split button which is visible when context pane is closed. I'll fix it.

**Comment by dstillman** [comment]
Not sure if this is unique to this PR but pressing Shift-Tab from Info is scrolling the PDF for me, seemingly to a random page. Let me know if you can't reproduce.

**Comment by dstillman** [comment]
This is great, except two (related) things:

1) Shift-Tab from the toolbar focuses the PDF view, not the right-hand pane (e.g., the last row in the item pane).
2) In the Info pane, tabbing beyond Extra focuses the PDF view rather than the toolbar (so if you hold down Tab you keep cycling back through the item pane).

**Comment by dstillman** [comment]
(The Shift-Tab thing would be good to fix but the other part isn't a blocker — we could open a separate ticket for that and merge this now.)

**Comment by mrtcode** [comment]
> Not sure if this is unique to this PR but pressing Shift-Tab from Info is scrolling the PDF for me, seemingly to a random page. Let me know if you can't reproduce.

I can't reproduce that. Maybe a video demonstrating this would help me to guess what could cause this.

**Comment by dstillman** [comment]
https://user-images.githubusercontent.com/783082/157833887-01e9f495-4f68-4c67-8900-8fca5240d85a.mov

**Comment by dstillman** [comment]
PDF is http://arxiv.org/abs/2203.04293

**Comment by mrtcode** [comment]
Oh, I guess it's focusing link annotations.

**Comment by mrtcode** [comment]
How about tabbing into note-editor? It currently focuses editor text, but when doing Shift-Tab you have to walk through all the toolbar buttons. Do we want to focus PDF view → return button instead?

**Comment by dstillman** [comment]
I think we have to? Having different tab orders in different directions seems pretty confusing in terms of accessibility.

**Comment by mrtcode** [comment]
Deficiencies that still exists:
- Shift-Tab on reader toolbar focuses context pane first focusable node, not the last one (for that we need to analyze content in each pane to determine which focusable node is the last one).
- Unnecessary border.
- RTL mode issues.
- Tab in note-editor doesn't jump anywhere.

**Pull request merged**
