### PR TITLE
Improve merge pane

### PR DESCRIPTION
**Pull request by windingwind**
resolve: #4142

### CODE REVIEW

**Comment by windingwind** [comment]
Now:

image

**Comment by yexingsha** [comment]
Looks good, just need to fix the merge button menu so that it doesn't hug the screen edge.

Current menu placement:

Screenshot 2024-06-03 at 23 26 19

Compared to regular item info context menu:

Screenshot 2024-06-03 at 23 39 38

**Comment by windingwind** [comment]
I think that's the toolbarbutton's default opening menu behavior on MacOS: the popup's top-left corner is placed at the bottom-left corner of the toolbarbutton.

image

If there is insufficient horizontal space for the menu, it will be shifted to the closest possible position.

image

**Comment by yexingsha** [comment]
We can indeed follow the macOS button menu behavior, but it's always positioned 6px from the edge of the screen:

macOS toolbarbutton menu

**Comment by windingwind** [comment]
I spent some time observing but still didn't find a way to control the menu popup's position when close to the screen edge. Only the context menus are positioned by the OS and have a gap between the screen edge, while the toolbarbutton's open menu popup behavior seems to be hardcoded in C++ (https://searchfox.org/mozilla-central/source/dom/xul/XULButtonElement.cpp#175) and we cannot mark the menupopup as native (context menu).

So maybe we can leave the menupopup position issue aside for now, if that's not a big problem?

**Comment by windingwind** [comment]
OK, it's using the info button behavior now.

**Comment by yexingsha** [comment]
Awesome!

**Pull request merged**
