### PR TITLE
Add note-editor text color picker

### PR DESCRIPTION
**Pull request by mrtcode**
Maybe we should use TinyMCE colors instead? It now uses default colors from `customcolorpicker.xul`.

#2433

### CODE REVIEW

**Comment by dstillman** [comment]
I think these colors are better, but there are too many. We should remove the two ugliest and/or most redundant colors from each row.

Probably also makes sense to flip vertically so black is in top left.

**Comment by dstillman** [comment]
A bunch of those still seem too close. I think we can remove more. Also should be horizontal, not vertical — closer to the click target.

These colors are much more pleasant than the TinyMCE ones. We could add an extra swatch that shows up if the color under the cursor isn't one of the hard-coded ones, and then it'd be active so you could use it elsewhere at the beginning of a line. (Is that possible? Does it make sense?)

**Comment by dstillman** [comment]
We can also refine this later, with, e.g., a row of recently used colors.

**Comment by mrtcode** [comment]
Ok, how about this:
Screenshot 2022-03-22 at 14 59 57

**Comment by dstillman** [comment]
👍

**Comment by mrtcode** [comment]
This was merged in 23a4a14b448ea6520bc51c01c1112e1170d2b812.

**Pull request closed without merging**
