### PR TITLE
quick-format: post-accessibility update edits

### PR DESCRIPTION
**Pull request by abaevbog**
- Backspace from the very beginning of the input will delete the previous bubble, as opposed to removing the input itself. If it makes it so that two inputs are next to each other, they are merged.
- When a new input is created via a mouse click, and the current input is empty, manually delete it right away. Waiting for the blur handler to remove it makes it so that the bubbles shift back and forth for a moment when a new input is added and the old input is not removed.
- Minor tweak to make sure that even if there's a 'br' before an input, clicking before it will not make a new input and just refocus it.

Fixes: #3749

### CODE REVIEW

**Comment by dstillman** [comment]
I'm now seeing a weird thing if I add a bubble and then press Backspace:

Screenshot 2024-02-27 at 6 00 48 PM

**Comment by dstillman** [comment]
And if I type something to get the full search results, accept that, and press Backspace:

Screenshot 2024-02-27 at 6 01 47 PM

**Comment by abaevbog** [comment]
That is ... odd. The reference panel should be explicitly cleared when an input becomes a bubble. 

I'm still trying to reproduce this and no luck yet. Is the reference selected with a mouse click or with an Enter? There are no other bubbles, this is a completely fresh dialog? And this is on a mac, right?

**Comment by abaevbog** [comment]
I have a guess that this could be caused by me reopening the panel when all is deleted but not re-runing the search (which also takes care of the panel resizing).

I just repushed with a small tweak to actually redo the search when all is deleted - does that fix it for you?

**Pull request merged**
