### PR TITLE
collection highlight tweaks

### PR DESCRIPTION
**Pull request by abaevbog**
- Substituted previous yellow highlight color for `--accent-yellow`
- On windows, do not trigger collection highlighting when input is focused so that copy-paste Ctrl-C/Ctrl-V do not trigger highlighting

Addresses:  #3643

### CODE REVIEW

**Comment by dstillman** [comment]
@yexingsha, this is `accent-yellow`?

Screenshot 2024-02-02 at 4 05 21 AM

At least in light mode, I think we want to keep this closer to the actual yellow it was before, not orange.

Screenshot 2024-02-02 at 4 09 03 AM

**Comment by yexingsha** [comment]
`accent-yellow` is used for icons, so it needs to be orange to provide enough contrast while maintaining saturation. Let's add a new `accent-highlight` for highlights in the collection tree, and perhaps also in the item tree for future multi-line search result functionality. Light version is `#ffea0080`, dark version is `#ffd40026`.

Sidebar-light Sidebar-dark

The yellow is a bit more orange so that it doesn't look greenish in dark mode.

**Comment by abaevbog** [comment]
Re-pushed. I think it looks great!

**Comment by dstillman** [comment]
Screenshot 2024-02-06 at 12 54 29 PM

Do we know why this is looking different?

**Comment by abaevbog** [comment]
Hm, I am honestly not sure... The HEX of the color `#ffea0080` is the same as in figma but it certainly looks a bit different. 
I took rgba of that color from figma and increased the opacity from 0.5 to 0.7. That second row looks a bit closer to what we see in figma, right? 

Screenshot 2024-02-06 at 2 04 17 PM


I am doing some googling now, and it seems this is something that has been brought up before: https://forum.figma.com/t/figma-colours-dont-match-web-export/20526/7

**Comment by yexingsha** [comment]
It's a color space issue, Figma uses sRGB color space while macOS uses P3 by default, so they can look different, especially when rendering opacity overlays. I use sRGB on my device, so the colors I see in the app are exactly the same as in Figma:

Screenshot 2024-02-06 at 14 07 38

And I think the P3 color looks fine, so let's keep the `#ffea0080` as is.

**Pull request merged**
