### PR TITLE
Add toCanonical and toLabel for Zotero.CharacterSets

### PR DESCRIPTION
**Pull request by aurimasv**

### CODE REVIEW

**Comment by aurimasv** [comment]
Should probably add tests. One minute

**Comment by aurimasv** [comment]
Ready

**Comment by dstillman** [comment]
So for what it's worth, these are the charsets we'll be losing if we prepopulate from these. Not sure if Firefox actually renders any of these properly anyway.

```
Unrecognized charset: adobe-symbol-encoding
Unrecognized charset: ansi_x3.4-1986
Unrecognized charset: cn-gb
Unrecognized charset: cn-gb-isoir165
Unrecognized charset: cp367
Unrecognized charset: cp850
Unrecognized charset: cp852
Unrecognized charset: cp855
Unrecognized charset: cp857
Unrecognized charset: cp862
Unrecognized charset: cp864
Unrecognized charset: csascii
Unrecognized charset: cshalfwidthkatakana
Unrecognized charset: cshppsmath
Unrecognized charset: csiso103t618bit
Unrecognized charset: csiso159jisx02121990
Unrecognized charset: csiso2022jp2
Unrecognized charset: csunicode11
Unrecognized charset: csunicode11utf7
Unrecognized charset: csunicodeascii
Unrecognized charset: csunicodelatin1
Unrecognized charset: cswindows31latin5
Unrecognized charset: extended_unix_code_packed_format_for_japanese
Unrecognized charset: ibm367
Unrecognized charset: ibm850
Unrecognized charset: ibm852
Unrecognized charset: ibm855
Unrecognized charset: ibm857
Unrecognized charset: ibm862
Unrecognized charset: ibm864
Unrecognized charset: iso-2022-jp-2
Unrecognized charset: iso-8859-1-windows-3.0-latin-1
Unrecognized charset: iso-8859-1-windows-3.1-latin-1
Unrecognized charset: iso-8859-2-windows-latin-2
Unrecognized charset: iso-8859-5-windows-latin-5
Unrecognized charset: iso-10646
Unrecognized charset: iso-10646-j-1
Unrecognized charset: iso-10646-ucs-2
Unrecognized charset: iso-10646-ucs-4
Unrecognized charset: iso-10646-ucs-basic
Unrecognized charset: iso-10646-unicode-latin1
Unrecognized charset: iso-ir-6
Unrecognized charset: iso-ir-103
Unrecognized charset: iso-ir-159
Unrecognized charset: iso646-us
Unrecognized charset: iso_646.irv:1991
Unrecognized charset: jis_x0201
Unrecognized charset: jis_x0208-1983
Unrecognized charset: jis_x0212-1990
Unrecognized charset: ks_c_5601
Unrecognized charset: t.61
Unrecognized charset: t.61-8bit
Unrecognized charset: unicode-1-1-utf-7
Unrecognized charset: unicode-2-0-utf-7
Unrecognized charset: us
Unrecognized charset: utf-7
Unrecognized charset: x-cns11643-1
Unrecognized charset: x-cns11643-2
Unrecognized charset: x-cns11643-1110
Unrecognized charset: x-dectech
Unrecognized charset: x-dingbats
Unrecognized charset: x-euc-tw
Unrecognized charset: x-gb2312-11
Unrecognized charset: x-imap4-modified-utf7
Unrecognized charset: x-jisx0208-11
Unrecognized charset: x-ksc5601-11
Unrecognized charset: x-mac-ce
Unrecognized charset: x-mac-greek
Unrecognized charset: x-mac-turkish
Unrecognized charset: x-tis620
Unrecognized charset: x-unicode-2-0-utf-7
Unrecognized charset: x0201
Unrecognized charset: x0212
```

**Comment by aurimasv** [comment]
Could you run a query on the server to see if there's a significant number of file attachments with these encodings?

**Comment by fbennett** [comment]
Not sure what the consequences of the change would be, but I certainly recognize "iso-2022-jp-2" (JIS), "extended_unix_code_packed_format_for_japanese" (EUC-JP), and "jis_x0208-1983" (shift-JIS) as Japanese encodings that are still in wide use (to the dismay of many). There has been progress in UTF-8 adoption in Japan, but there are a LOT of important relics about, including this site, which is our primary source for the text of statutory law (!):

    http://law.e-gov.go.jp/cgi-bin/idxsearch.cgi

As you can see, it's encoded from top to bottom in shift-JIS (some have another name for it, but that's another story).

I really hate to say it, but retaining support for these particular legacy encodings continues to be important here. The same is probably also true of several other Asian-script jurisdictions. In the case of the Japanese encodings, Firefox will render all three correctly with a correct charset declaration.

**Comment by dstillman** [comment]
Well, the issue is largely whether those specific names above are used. If you look at the mappings in the commit, you can see that EUC-JP and Shift-JIS are supported, with various aliases. I assume the Encoding Spec had reasons for not including the above names, but I haven't looked into it.

I'll run some queries on the server to see if the above names do indeed show up.

**Comment by aurimasv** [comment]
Shift_JIS support is maintained though, but jis_x0208-1983 is not recognized as the legacy label for this encoding. I'll have to look around and see if we should include some of these missing labels into the encoding map.

I know that UTF-7 support has been long gone from Firefox (since version 5, I think), so not all of these need to be maintained.

**Comment by fbennett** [comment]
Sorry, I didn't realize it was just the mappings at issue. Those names for them do look unfamiliar.

**Pull request merged**
