### PR TITLE
Fix item pane width jumping in stacked mode

### PR DESCRIPTION
**Pull request by windingwind**
fix: #4755

### CODE REVIEW

**Comment by windingwind** [comment]
Should explicitly set a width for the container element of the item pane, otherwise its inner elements, e.g. title and abstract, can stretch the width of item pane.

**Comment by dstillman** [comment]
This is now kind of more messed up for me:

Screenshot 2024-10-15 at 6 37 32 AM

**Comment by windingwind** [comment]
Does it works for you now? The stacked layout does not rely on persisted width attributes and thus should be more robust.

**Comment by dstillman** [comment]
Fixed, but now the splitter no longer tracks the mouse cursor as you resize it. Can we fix that?

https://github.com/user-attachments/assets/bdfc6939-e7dd-4eb6-acaf-25b2903e57a0

**Comment by dstillman** [comment]
I'll merge this for now, since it's better than before.

**Comment by windingwind** [comment]
> Fixed, but now the splitter no longer directly tracks the mouse cursor as you resize the panes. Can we fix that?
> 
>  splitter.mov

We need all layout components to be flex so that they can be shrunk by window resizing. For flex elements, the assigned `width`/`height` works as a relative ratio to their neighbor elements, instead of an absolute value, while the value of width/height is from the mouse. That's why the splitter does not track the mouse cursor. I guess that's the behavior of the builtin splitter system.

**Pull request merged**
