### PR TITLE
Fix scaffold window UI

### PR DESCRIPTION
**Pull request by windingwind**
fix: #4258

### CODE REVIEW

**Comment by yexingsha** [comment]
Looks good! Just a couple of small issues:

1. The text in tabs shift around slightly when different tabs are selected.

2. Buttons still have too much horizontal margin. For example, in the Tests tab, the Delete button should be aligned with the left edge of the input boxes, and the spacing between buttons should be 8px.

3. The Metadata tab seems to have a slightly larger left padding.

**Comment by windingwind** [comment]
Thanks! Fixed:

image

image

**Comment by yexingsha** [comment]
Much better now! Looking at the list of tests, I just realized that the columns aren't aligned with their headers. Is it possible to use our virtualized table style here?

**Comment by windingwind** [comment]
Unfortunately, it is not possible to fix the misalignment unless we replace the `richlistbox` with our v-table.

**Comment by yexingsha** [comment]
Ah, I see. This is not super important, so let's just keep it as is for now.

**Comment by Geo123abc** [comment]
problem: [selectitems.xhtml can't  render correctly](https://groups.google.com/g/zotero-dev/c/s9xPbtjYXfk)

@zzlb0224 found that adding [width: 100%](https://github.com/zotero/zotero/blob/174bde74516f7a5a739845d69f6d4233ca0ecb60/scss/components/_richlistbox.scss#L33) will make the image fill the container. If the label still has overflow: hidden;, it will be hidden, showing as follows:

**Comment by windingwind** [comment]
@Geo123abc thanks, should be fixed in b16bbc4.

**Comment by dstillman** [comment]
Fixed in beta 100

**Pull request merged**
