### PR TITLE
fix the translation of "note" for Chinese

### PR DESCRIPTION
**Pull request by specter119**
translate note to 注视 is a little spell mistake here.

### CODE REVIEW

**Comment by dstillman** [comment]
Thanks — I've made this change [on Transifex](https://www.transifex.com/zotero/zotero/). (You're welcome to contribute further edits there.)

**Comment by specter119** [comment]
@dstillman thanks, I will.

**Comment by specter119** [comment]
@dstillman I'm glad to attend to the zotero group on Transifex for chinese Translation, but I haven't got the approval since I requested to attend in.

**Comment by dstillman** [comment]
Sorry about that — I've approved you.

**Comment by specter119** [comment]
@dstillman Thanks

**Pull request closed without merging**
