### PR TITLE
Document preferences cleanup

### PR DESCRIPTION
**Pull request by adomasven**
Before:
<a href="https://cloud.githubusercontent.com/assets/5899315/25622282/993840d8-2f5c-11e7-9bf5-d5fdc584364e.png"></a>

Now: 
<a href="https://cloud.githubusercontent.com/assets/5899315/25622241/7aa352a2-2f5c-11e7-9f70-da6cb2735f48.png"></a>

### CODE REVIEW

**Comment by adam3smith** [comment]
Is it actually the case that for bookmarks "The document needs to be saved in doc/docx format"? -- I haven't tested, but I'm surprised that's the case.

**Comment by adam3smith** [comment]
(otherwise yay for this)

**Comment by dstillman** [comment]
Combined "The document must be saved in the .doc or .docx file format." with the previous string.

"Footnotes" should be lowercase (and should we add "endnotes" back?).

Switch order of "footnotes" and "accidentally modified".

How easy is it to modify bookmarks accidentally? Is that why we recommend ReferenceMarks?

**Comment by adomasven** [comment]
> Is it actually the case that for bookmarks "The document needs to be saved in doc/docx format"? -- I haven't tested, but I'm surprised that's the case.

Probably not, but currently the plugins listen for saves and warn if you are trying to save as .odt with bookmarks, so I haven't tested. Possible that Word might lose bookmarks when opening .odt. But I'll check this out.

> How easy is it to modify bookmarks accidentally? Is that why we recommend ReferenceMarks?

We recommend ReferenceMarks/Fields for LO/Word. Yes, bookmarks are very modification non-resistant. Sometimes you can modify the bookmark by starting to type directly after the inserted citation, but the whole bookmark system in how it works is magic to me still, so I cannot comment. However, we've had people send in very broken bookmark-based documents, where once they get corrupt, they get very very badly corrupt and it's very hard to recover from. Furthermore, you cannot add field shading for bookmarks, like you can for ReferenceMarks/Fields, so you can't even tell what's up with straight-up doc examination.

**Comment by dstillman** [comment]
> Possible that Word might lose bookmarks when opening .odt.

This sounds vaguely familiar, FWIW.

**Comment by adomasven** [comment]
> Combine "The document must be saved in the .doc or .docx file format." with the previous string.

<a href="https://cloud.githubusercontent.com/assets/5899315/25652379/9a589fc8-2ff0-11e7-94d1-ba3f309aadfd.png"></a>

I'm not sure about this. The discussion in zotero/zotero-word-for-windows-integration#30 focused precisely on making the dialog less wordy and intimidating. This is okay:

<a href="https://cloud.githubusercontent.com/assets/5899315/25652531/56dc80ba-2ff1-11e7-933d-9343d32d44ac.png"></a>

**Comment by dstillman** [comment]
All right, I guess if we have those for both it's OK — there's a line for features/limitations and then another line for the document format.

We could probably say "saved as an .odt" and "saved as a .doc or .docx" — "the .odt file format" seems a bit technical.

And maybe you're right that "or endnotes" is unnecessary. If you see that they can't be saved as footnotes, you're probably not going to be shocked when they don't work in endnotes either, right?

**Comment by rmzelle** [comment]
Two more nitpicks:

* Should the window title be changed from "Document Preferences" to "Zotero Document Preferences" to indicate context?
* Dan and Sebastian both agreed with me that changing "Format Using:" to e.g. "Store Citations as:" would be an improvement. Can you make that change as well? See https://github.com/zotero/zotero-word-for-windows-integration/issues/30#issuecomment-285139567.

**Comment by adomasven** [comment]
@rmzelle thanks! [Updated](https://github.com/zotero/zotero/commit/b80cdb2915cad5312a8874a67fe0b8afb2ae6ac9)

**Comment by gracile-fr** [comment]
> Should the window title be changed from "Document Preferences" to "Zotero Document Preferences" or "Zotero - Document Preferences" to indicate context?
I agree (<a href="https://github.com/zotero/zotero/blob/b80cdb2915cad5312a8874a67fe0b8afb2ae6ac9/chrome/locale/en-US/zotero/zotero.dtd#L190">here's the string</a>).

**Comment by rmzelle** [comment]
(@gracile-fr, @adomasven already made that change by programmatically prepending the client name (i.e. Zotero) before the original window title: https://github.com/zotero/zotero/commit/b80cdb2915cad5312a8874a67fe0b8afb2ae6ac9#diff-3af4d2a3f7cf404fa9befc1d27591570R148)

**Comment by gracile-fr** [comment]
ah indeed, I had only looked at the localized files… thanks!

**Comment by bwiernik** [comment]
> Is it actually the case that for bookmarks "The document needs to be saved in doc/docx format"? -- I haven't tested, but I'm surprised that's the case.

@adamsmith I looked into that—Word opens .odt Files as read-only. You have to convert to doc(x) or Save As to keep as odt. As the only reason to use Bookmarks is to move between Word and LO, it makes sense to just say that doc(x) is required.

**Pull request merged**
