### PR TITLE
 Reduce contrast of alternating row colors 

### LINKED ISSUE #3635: Reduce contrast of alternating row colors
To match macOS

### PR DESCRIPTION
**Pull request by yexingsha**
Closes #3635

### CODE REVIEW

**Comment by dstillman** [comment]
Is this meant to change light mode on macOS? I'm not seeing a difference there.

**Comment by dstillman** [comment]
Dark mode looks good, though.

**Comment by yexingsha** [comment]
Light mode was already the same as macOS, so no change there.

**Comment by dstillman** [comment]
You mean as Finder? It's not exactly the same, at least for me, though maybe that's color management doing something different:

Screenshot 2024-02-02 at 2 44 38 AM

#f4f5d5 vs. #f2f2f2

**Pull request merged**
