### PR TITLE
Fix main window layout and window resizing

### PR DESCRIPTION
**Pull request by windingwind**
fix: #4669
Replace flex attribute with flex-shrink and flex-grow style
to allow elements to be resized by splitter and window resizing.
Set the max-width on collections pane
to prevent it from pushing other panes outside window border
Set the min-width on window according to
the size of both library and reader tabs

### CODE REVIEW

**Comment by dstillman** [comment]
This doesn't seem to be doing anything for me. I drag the right edge of the window to the left and it just stops in the normal place, without switching into Stacked.

I'm also getting logged warnings in the console, which may or may not be from this:

```
Error in parsing value for ‘width’.  Declaration dropped.
```

**Comment by windingwind** [comment]
No it's not. From my understanding, we want to collapse the item pane in the library to stack layout because it cannot be shrunk by dragging the window to a smaller size, which makes the window too wide if the item pane is very wide (e.g. when you leave the maximized window - the item pane is never resized unless you manually drag the splitter).

Now that this PR allows all layout components to be resized to their min-width while resizing the window, the window itself will never be ridiculously wide, and thus I think it resolves the original issue and there is no need to introduce the auto-stack.

**Comment by windingwind** [comment]
We can set a smaller min-width to the left/right pane to make the window fit the half-screen width on a regular laptop screen, e.g. 1080/2 px. I guess we discussed before, about setting the min-width of the collections pane to 100px or so.

But if that's not enough, we can do the auto-stack thing. I didn't add it here, as the changes in this PR seem to be more fundamental. It would be easy to add the auto-stack based on this PR, and I guess it would be better to be a separate PR/commit.

**Comment by dstillman** [comment]
This is great. One glitch: in a reader tab, if the context pane is closed and I make the window narrow, the context pane reappears on the bottom.

**Comment by dstillman** [comment]
But yes, we can make the collections pane min-width smaller. I don't think we can really make the item pane smaller, due to the creator row buttons.

**Comment by dstillman** [comment]
(The width of the field labels also varies by locale, and I think some are wider than English.)

**Comment by windingwind** [comment]
How about decreasing the min-width of the items tree from 370px to 200px or 250px?

As for the item pane, we could use some icons for field labels when the item pane is narrow so that it can free 100 or 150 more px.

**Comment by dstillman** [comment]
Let's start with just decreasing the collections min-width and the auto-stack.

**Comment by dstillman** [comment]
(We're definitely not going to start swapping out field labels for icons, and the auto-stack makes reducing the items list well past the point of usability unnecessary.)

**Comment by windingwind** [comment]
OK, the collections pane is now 100px min-width.

I noticed that actually many JS layout tricks we used before aren't necessary. Replacing the `flex=1` attribute with `flex-grow` and `flex-shrink` along with `min-width: 0` can perfectly layout the elements, e.g. collection search textbox.

**Comment by dstillman** [comment]
Hmm, this is actually much weirder. As I narrow the window, the collections pane narrows to be totally useless — just the icon plus one character — and then snaps back to a much larger size when stacked mode turns on.

If we're using auto-stack, I don't think super narrow, useless min-widths make sense. Narrow window widths are a genuinely good reason to use stacked mode, so let's just embrace it and keep the min-width we had before.

**Pull request merged**
