### PR TITLE
Use the label Programming Language

### PR DESCRIPTION
**Pull request by zuphilip**
This should use the same label as in searchConditions.programmingLanguage.

See also https://forums.zotero.org/discussion/78907/programming-language-is-labeled-as-language-only

### CODE REVIEW

**Comment by dstillman** [comment]
Maybe we should abbreviate this as "Prog. Language"? Not that elegant, but neither is this:

field1

vs.

field2

**Comment by zuphilip** [comment]
Yeah, I guess that would be better. There is also `Loc. in Archive` which is abbreviated. However, in other languages it might be different, e.g. `Programmiersprache` is equally long as `Standort im Archiv` or `Heruntergeladen am`.

Should I change to `Prog. Language`?

**Comment by dstillman** [comment]
> Should I change to Prog. Language?

Yeah, let's do that.

**Comment by zuphilip** [comment]
Done

**Pull request merged**
