### PR TITLE
Fixed _handleRelated for web translators

### PR DESCRIPTION
**Pull request by Droitslinguistiques**
Rewrote commented-out code and fixed it so that seeAlso array item get related in Zotero when saved.

### CODE REVIEW

**Comment by dstillman** [comment]
Thanks, but please stop creating new PRs. If you want to edit a PR, you can push to the same branch.

**Comment by Droitslinguistiques** [comment]
I'm sorry, I keep screwing up. I accidentally renamed a branch and it broke everything, so I deleted my forked repository and tried to start again. This happened twice. So I'm sorry.

**Comment by Droitslinguistiques** [comment]
So, it turns out that my "fix" for web translators adding related items broke something with saving notes. 

As I said in the forums, I'm way out of my depth here. I'm afraid I'll have to rely on someone more skilled than me to figure out how to get both working correctly.

**Comment by Droitslinguistiques** [comment]
There, should be all good now. At least I hope.

**Comment by Droitslinguistiques** [comment]
@dstillman is there anything I can do to help check whether this fix can be implemented?

**Comment by Droitslinguistiques** [comment]
Hey, sorry to bug you again, but I'm just checking-in to see if you had had a chance to look at this.

**Pull request closed without merging**
