### PR TITLE
Fix Library Lookup and Locate Engines Lookup

### LINKED ISSUE #744: Library lookup saves item (twice) instead of performing lookup

### PR DESCRIPTION
**Pull request by zuphilip**
* This resolves #744.
 * Changed private function `_constructLookupFunction` and its calls. Add there also stopPropagation() function.

### CODE REVIEW

**Comment by simonster** [comment]
I was just about to look into this, thanks! But couldn't we just make the function returned by `_constructLookupFunction` call `e.stopPropagation()` at the end, instead of doing this reorganization?

If we are going to reorganize things in this way, then `_constructLookupFunction` should be renamed, since it's no longer constructing a function.

**Comment by zuphilip** [comment]
I think there are two errors currently: For one the lookup is not working and second the "parent" function is called (sometimes even twice). The `stopPropagation` will solve the second problem and could also be moved somewhere else. However, I couldn't exactly find out what causes the first problem (and I tried several things...).

I thought about renaming the function. Because all the lookup specific stuff are in the other part. Moreover, I think to remember that there migth be other ideas to include in this menue where maybe this function may be suitable.

**Comment by zuphilip** [comment]
A suggestion for renaming: `performAfterTranslation`.

**Comment by simonster** [comment]
@zuphilip This patch appears to be sufficient on my system:

```
diff --git a/chrome/content/zotero/browser.js b/chrome/content/zotero/browser.js
index 518f21b..35ee645 100644
--- a/chrome/content/zotero/browser.js
+++ b/chrome/content/zotero/browser.js
@@ -732,6 +732,7 @@ var Zotero_Browser = new function() {
                        Zotero_Browser.progress.show();
                        Zotero_Browser.progress.changeHeadline(Zotero.getString("ingester.lookup.performing"));
                        tab.page.translate.translate(false);
+                       e.stopPropagation();
                }
        }
        
diff --git a/t
```

Is there a case where that doesn't work?

**Comment by zuphilip** [comment]
My test cases are http://www.amazon.de/dp/0141036141/ and http://www.worldcat.org/title/nineteen-eighty-four/oclc/842042029 . They still fail with your patch to perform the lookup on my FF 38.0.1, Win 7, with Zotero based on branch `4.0` latest commit https://github.com/zotero/zotero/commit/4b995dd467b8e51e4e05c8673a7205cbff22be30 + 3 lines from your patch.

**Comment by simonster** [comment]
Both of those work for me with that patch on both OS X and Win 8.1, also with FF 38.0.1. If there is a difference in the behavior of that patch and this PR, I'd like to know what it is. It looks to me as though they should be functionally identical.

**Comment by zuphilip** [comment]
Ui, I was misreading your `diff`. Sorry. You are right, this works the same.

**Pull request closed without merging**
