### PR TITLE
Switch Advanced Search window to React

### PR DESCRIPTION
**Pull request by fletcherhaz**

### CODE REVIEW

**Comment by fletcherhaz** [comment]
Currently status of things still not done/tested:
- Saving search/editing later
- Submenus/tooltips
- Autocomplete
- Styling needs to be cleaned up and tested on all platforms
- The files are sort of all over the place
- Go over zoterosearch.xml and double check we have everything

**Comment by adomasven** [comment]
This will introduce merge conflicts as far as changes to how the item tree in the advanced search dialog works

**Comment by fletcherhaz** [comment]
I've left the item tree entirely alone and didn't see anything in #1827 that would interfere. The window is still XUL it just has two HTML elements inside it for the search conditions and buttons. Can you be more specific about what conflicts you see?

**Comment by AbeJellinek** [comment]
Superseded by #2631.

**Pull request closed without merging**
