### PR TITLE
Item Tree: Attempt to fix OS font scaling

### LINKED ISSUE #2381: HTML tree: Fonts are cut off with certain OS font settings
https://forums.zotero.org/discussion/94852/field-size-not-displaying-correctly

Maybe we can better handle this?

### LINKED ISSUE #2450: Extra column shows sliver of second line
https://forums.zotero.org/discussion/95484/display-issue-multiple-lines-in-extra-column

I guess in theory this would happen with any multiline value displayed in the tree.

### PR DESCRIPTION
**Pull request by adomasven**
Closes #2381, closes #2450

A slight rethinking to the way row heights are specified for the item tree. They will now be specified in multiples of lines of text we expect to render for whatever the CSS and then OS-level font-scaling expected rendered font size for the tree rows is. The default is 1 line of text per one row. This is required to deal with OS-level font-scaling. A side effect of this is that row-heights may be slightly different for different font-sizes (as chosen in the Zotero interface) when compared to before with the XUL tree. I've also set a minimum row height of 20px. Tested on all platforms and looks fine to me.

### CODE REVIEW

**Comment by dstillman** [comment]
Bumped up a couple font sizes on macOS, this is way tighter. Is this adjustable?

Screen Shot 2022-03-29 at 12 39 09 AM

Screen Shot 2022-03-29 at 12 37 36 AM

**Comment by dstillman** [comment]
(What we had before might have been too much, but this is definitely too tight.)

**Comment by adomasven** [comment]
I've updated it with percentage-based padding.

**Comment by A11en0** [comment]
Sorry, it does not work on my computer:

System: Debian 10
Zotero Version: 6.0.4

image

**Comment by dstillman** [comment]
@A11en0: The fix is in the <a href="https://www.zotero.org/support/dev_builds">Zotero beta</a>, not in 6.0.4. It will be included in 6.0.5 soon.

Please post all bug reports, feature requests, and other feedback to the <a href="https://forums.zotero.org/">Zotero Forums</a>, not GitHub.

**Pull request merged**
