### PR TITLE
Fixed dark theme toolbar on Linux/Middle Click to close tab functionality

### PR DESCRIPTION
**Pull request by N-Be**
Fixes issue #1999 

Before:

After:

### CODE REVIEW

**Comment by N-Be** [comment]
I dont know how to edit pull requests I'm new to working on actual software but I meant to make a separate pull request for the middle click to close tab issue #1993

**Comment by hzhangxyz** [comment]
Is there any update this pr? Currently the ugly ui for dark theme is really annoying

**Comment by eldar** [comment]
Using Zotero 6 Beta (5.0.97-beta.33+fdcd4e51c) on KDE with a dark theme (Breezy Dark) and rendering of panels and tabs is as if it is a bright theme:

image

**Comment by dstillman** [comment]
This messes up the toolbar design on other OSes. We'll need a version that is limited to Linux. It also shouldn't change the design in light mode in any way. (I didn't check to see if this does.)

Also please remove rebase and remove the middle-click commit.

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/111074/available-for-beta-testing-zotero-redesigned/p1

**Pull request closed without merging**
