### PR TITLE
Add option to cite shortDOIs instead of full DOIs

### PR DESCRIPTION
**Pull request by bwiernik**
Closes https://github.com/zotero/zotero/issues/1702

### CODE REVIEW

**Comment by bwiernik** [comment]
Note that this will work with citeproc-js for both item types with proper DOI fields and DOI stored in Extra.

**Comment by bwiernik** [comment]
@dstillman Do you have any comments on this? I'd like to update DOI Manager to store shortDOIs in Extra rather than the DOI field to stop it from interfering with Retraction notices, etc., but I can't really do that without this being merged/

**Comment by dstillman** [comment]
Do shortDOIs still have any institutional backing, beyond a service that hasn't been taken down ("Updated 2 April 2013")? Wondering about, e.g., [this thread](https://twitter.com/thunkenizer/status/1043180863155056641), where @mfenner questions their long-term future.

DOI Manager should certainly switch to storing shortDOIs in Extra, and this option could be implemented in DOI Manager as well, with fairly trivial monkey-patching of `retrieveItem()`.

(There's also a typo in this patch, such that it will never work. `shorDOI = […]` should be `let shortDOI = […]`.)

**Comment by mfenner** [comment]
shortDOIs have been deprecated by the DOI Foundation. I haven't seen any significant activity around using them, and I personally think supporting them leads to more confusion than being helpful to users.

**Comment by bwiernik** [comment]
Monkey-patching is a bit beyond my knowledge. Do you have a toy example of a monkey patch I could look as a model?

**Comment by dstillman** [comment]
Most of BBT, I believe. We don't particularly recommend it, since it's inherently fragile, but it's how @retorquere makes changes to lots of native functionality. The basic idea is that you save a reference to a function and replace it with a wrapper method that calls the original and modifies the input or (more likely) the output. In this case, you'd overwrite `retrieveItem()`, call your stored reference to the original function with the same arguments, and just apply the same modification to its return value that you're doing now, and then return that.

Untested, but it'd be something like this:

```javascript
function wrapRetrieveItem() {
	var origFunc = Zotero.Cite.System.prototype.retrieveItem;
	Zotero.Cite.System.prototype.retrieveItem = function () {
		var cslItem = origFunc.apply(Zotero.Cite.System.prototype, arguments);
		if (!Zotero.Prefs.get("export.useShortDOI")) {
			// substitute shortDOI for DOI if supplied
			let shortDOI = cslItem.extra.match(/^short\s?doi:\s*(.+)/mi);
			if (shortDOI) {
				cslItem.DOI = shortDOI[1];
			}
		}
		return cslItem;
	};
}
```

**Comment by dstillman** [comment]
(Thanks, @mfenner.)

**Comment by bwiernik** [comment]
Thanks @dstillman

**Comment by retorquere** [comment]
BBT has enough of them that I've written a function to do it 🙄 .

I'd go as far as actively recommending against monkey-patching if it can be at all avoided. It makes the work for Zotero support harder, and you need to keep vigilant yourself that you understand very keenly the assumptions that the code you're patching makes, and what assumptions code that calls it makes, and that you can always still satisfy those. I've made a fair bit of gaffes, and that cost more often than it should falls to the Zotero developers.

That said, the basics are very simple. If you have

```
const marker = 'MyExtensionHasMonkeyPatched'

export function patch(object, method, patcher) {
  if (object[method][marker]) return
  object[method] = patcher(object[method])
  object[method][marker] = true
}
```

you can then do

```
patch(Zotero.Item.prototype, 'getField', original => function (field, unformatted, includeBaseMapped) {
  try {
    if (field === 'citekey') return 'fixed'
  } catch (err) {
    Zotero.debug(`patched getField:${err.message}`)
  }

  return original.apply(this, arguments)
})
```

it works the same for `async` functions (or any `coroutine`-wrapped equivalent):

```
patch(Some.object, 'method', original => async function (arg1, arg2) {
  await someStuff()
  return await original.apply(this, arguments) // or just return original.apply(this.arguments) if it's last
})
```

**Comment by retorquere** [comment]
("Most of BBT" is fortunately no longer the case. I have 15 monkey patches in total currently)

**Comment by bwiernik** [comment]
Thanks Emiliano! Much appreciated.

**Pull request closed without merging**
