### PR TITLE
Fix item pane header

### PR DESCRIPTION
**Pull request by windingwind**
fix: #4141
Move split-menu-button styles to SCSS

- [x] There is currently almost no spacing between the title area and the buttons. Should be 4px in tight, and 8px in comfortable
- [x] Decrease the margins around and between the buttons to 8px
- [x] Improve the paddings of the two buttons. They are meant to look like system native buttons, but right now they look slightly off on both mac and windows. The padding before the icon in "Add to My Library" is especially large
- [x] ~~Are the quotation marks around "My Library" necessary? I think we can remove those~~
- [x] We should use accent-blue for the library icon
- [x] The color of the divider and the chevron are both wrong in dark mode

### CODE REVIEW

**Comment by windingwind** [comment]
fix: #4116

**Comment by windingwind** [comment]
Hi @yexingsha, this is what this PR looks like, please check if I missed anything:

MacOS:

image
image


Windows:
image
image

**Comment by yexingsha** [comment]
On macOS, the text and icon are positioned 1px too high within the button (it's more obvious with the library icon). And both the spacing and padding are still a bit too large. Seems like the extent of the button is about 2px wider than its optical width, so need to compensate for that:

Screenshot 2024-05-29 at 17 25 44





The spacing between the icon and text can be reduced to 4px.



The header looks much better now at narrow width, but looks weird at larger width:

Screenshot 2024-05-29 at 16 31 51

I think once the "Add to" button grows wide enough to fully display the text, both buttons should grow in width as the pane gets wider. And perhaps the split menu button should still align to center, even though it does go against convention.

**Comment by windingwind** [comment]
Thanks. Done:

- [x] the text and icon are positioned 1px too high within the button
- [x] And both the spacing and padding are still a bit too large. Seems like the extent of the button is about 2px wider than its optical width, so need to compensate for that
- [x] The spacing between the icon and text can be reduced to 4px.
- [x] And perhaps the split menu button should still align to center, even though it does go against convention.
- [x] I think once the "Add to" button grows wide enough to fully display the text, both buttons should grow in width as the pane gets wider

https://github.com/zotero/zotero/assets/33902321/670b5f6a-c343-40dc-8aa6-c7a709e2edbc

**Comment by yexingsha** [comment]
This looks great!

**Pull request merged**
