### PR TITLE
Quick-format: do not hide reference panel

### PR DESCRIPTION
**Pull request by abaevbog**
- Reference panel remains opened while the focus is on an input
- The first item from the reference panel is no longer selected by default to avoid unwanted items being added as a bubble
- The first item from the reference panel is selected only when the dialog has no bubbles or when a search for a non-empty input just ran
- Shift-Enter from input or reference panel will accept the dialog's state instead of creating a bubble
- Ensure that the reference panel reloads when a bubble is deleted

Addresses: #3811, #3671

### CODE REVIEW

**Comment by abaevbog** [comment]
I also attempted to add a button to accept the dialog - not sure about the exact icon and positioning though.

Screenshot 2024-03-08 at 2 04 19 PM

I didn't add any keyboard nav onto that button yet - I'm not totally sure it's required. Now Enter doesn't always add the first item from the ref panel and Shift-Enter always accepts the dialog, so it seems to me it will always take longer to tab your way to the accept button and to click Space/Enter than to just press Enter (or Shift-Enter in the worst case). 

If we do want that button focusable, what would be the best way to get to it? Shift-Tab from a bubble/input focuses the Z-icon, so we could plug the "accept" button into that chain. First Shift-Tab focuses the accept button, second Shift-Tab focuses the icon?

**Comment by adomasven** [comment]
image

The accept button padding is wrong on linux.

If you arrow down to select an item, then arrowing back up should go back to the text field and unselect the selection, so that you can accept the dialog with Enter.

**Comment by abaevbog** [comment]
> The accept button padding is wrong on linux.

Thank you, I think it's nicer now. It should align with the Z icon on all platforms.

> If you arrow down to select an item, then arrowing back up should go back to the text field and unselect the selection, so that you can accept the dialog with Enter.

Oh yeah, good point! Now the navigation between input and the reference panel feels way smoother.

**Comment by adomasven** [comment]
> > The accept button padding is wrong on linux.
> 
> Thank you, I think it's nicer now. It should align with the Z icon on all platforms.


The right-padding is still too much (see screenshot above). Are you not seeing this on your Linux setup?

**Comment by abaevbog** [comment]
> The right-padding is still too much (see screenshot above). Are you not seeing this on your Linux setup?

Apologies, I do. Somehow I missed it at first and just focused on the vertical alignment (that was also off). 

I tried to set equal widths for Z/spinner/accept icons, and then dynamically set the editor's width to fill out the remaining space. I think it worked out. Alternatively, we could manually set the widths for each platform individually but this felt more general and less hacky to me.  

This is what it looks like on my end. The 'accept' button should be aligned with the Z-icon.

Linux:
qf_linux
Windows:
qf_win
Mac:
qf_mac

**Pull request merged**
